# Site settings
title: tueday.js
email: justin@jws.io
description: "javascript club. every tuesday."
baseurl: "/tuesdayjs/"
url: "http://thefivetoes.com"

# Build settings
markdown: kramdown
permalink: pretty
